version: '3.4'

services:
  lanchonete:
    image: lanchonete
    build: .
    container_name: local-lanchonete
    restart: always
    ports:
      - 192.168.1.31:7070:8080
    environment:
      ambiente: dev
      data_base_url: jdbc:postgresql://192.168.1.31:5432/lanchonete
      data_base_user: trainee
      data_base_password: 123